apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-pvc
  namespace: harbor
  labels:
    app: harbor
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: gp2
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      app: harbor  # Binds to our labeled PV
