apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-configmap
  namespace: harbor
data:
  HARBOR_ADMIN_PASSWORD: "Harbor12345"
  HARBOR_DATABASE_URL: "postgres://harbor:password@postgresql:5432/harbor"
  HARBOR_LOG_LEVEL: "info"
  HARBOR_STORAGE_TYPE: "filesystem"
  HARBOR_STORAGE_PATH: "/data"
  HARBOR_BASE_URL: "https://harbor.yourdomain.com"
