apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jobservice-pvc
  namespace: harbor
  labels:
    app: harbor
    component: jobservice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
