apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portal-pvc
  namespace: harbor
  labels:
    app: harbor
    component: portal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
