apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
  namespace: harbor
  labels:
    app: harbor
    component: database
spec:
  capacity:
    storage: 50Gi  # Minimum recommended for production
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain  # Critical for database
  csi:
    driver: ebs.csi.aws.com  # For AWS (use azure-disk for Azure, pd.csi.storage.gke.io for GKE)
    fsType: ext4
    volumeAttributes:
      encrypted: "true"  # Enable encryption
