apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: harbor
  labels:
    app: harbor
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
      storageClassName: gp2
  volumeName: postgresql-pv  # Explicit binding
