apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
  namespace: harbor
  labels:
    app: harbor
    component: registry
spec:
  capacity:
    storage: 50Gi  # Minimum recommended for registry storage
  accessModes:
    - ReadWriteMany  # Required for registry scaling
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain  # Critical for registry data
  csi:
    driver: efs.csi.aws.com  # EFS for RWX (EBS doesn't support ReadWriteMany)
    volumeHandle: [YOUR_EFS_FILESYSTEM_ID]
    volumeAttributes:
      provisioningMode: efs-ap
      fileSystemId: [YOUR_EFS_FILESYSTEM_ID]
      directoryPerms: "700"
    fsType: ext4
