apiVersion: v1
kind: Secret
metadata:
  name: harbor-secrets
  namespace: harbor
  labels:
    app: harbor
    heritage: helm
type: Opaque
data:
  # Core secrets
  CORE_SECRET: {{ randAlphaNum 32 | b64enc | quote }}
  JOBSERVICE_SECRET: {{ randAlphaNum 32 | b64enc | quote }}
  REGISTRY_HTTP_SECRET: {{ randAlphaNum 32 | b64enc | quote }}

  # Database credentials
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresPassword | default "defaultpassword" | toString | b64enc | quote }}

  # Redis password
  REDIS_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}

  # Registry storage (if using S3)
  REGISTRY_STORAGE_S3_ACCESSKEY: {{ .Values.registry.storage.s3.accessKey | default "" | toString | b64enc | quote }}
  REGISTRY_STORAGE_S3_SECRETKEY: {{ .Values.registry.storage.s3.secretKey | default "" | toString | b64enc | quote }}

  # Trivy adapter
  TRIVY_ADAPTER_REDIS_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}

  # Notary secrets (if enabled)
  NOTARY_SERVER_HTTP_SECRET: {{ randAlphaNum 32 | b64enc | quote }}
  NOTARY_SIGNER_HTTP_SECRET: {{ randAlphaNum 32 | b64enc | quote }}
