apiVersion: v1
kind: PersistentVolume
metadata:
  name: trivy-pv
  namespace: harbor
  labels:
    app: harbor
    component: trivy
spec:
  capacity:
    storage: 5Gi  # Recommended for vulnerability database
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  persistentVolumeReclaimPolicy: Retain  # Preserve vulnerability DB
  hostPath:
    path: /data/trivy
    type: DirectoryOrCreate
