apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trivy-pvc
  namespace: harbor
  labels:
    app: harbor
    component: trivy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
      storageClassName: gp2
  volumeName: trivy-pv  # Explicit binding
